"""Initial_migrate

Revision ID: b1569ad77244
Revises:
Create Date: 2025-10-15 19:04:19.434729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1569ad77244"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_categories",
        sa.Column("id", sa.Integer(), nullable=False, comment="Автоинкрементный ID категории"),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Уникальное имя категории (например: 'entertainment', 'work')",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="Уникальный идентификатор пользователя (UUID4)"),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="Email для авторизации (может быть NULL для анонимов)",
        ),
        sa.Column(
            "password",
            sa.String(length=255),
            nullable=True,
            comment="Хэш пароля (bcrypt/scrypt); NULL для анонимных пользователей",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время регистрации (UTC)",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время soft-delete (если не NULL — пользователь удалён)",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "attention_events",
        sa.Column("id", sa.Integer(), nullable=False, comment="Автоинкрементный ID события"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя, которому принадлежит событие"),
        sa.Column("domain", sa.String(length=255), nullable=False, comment="Домен, на котором произошло событие"),
        sa.Column(
            "event_type",
            sa.String(length=10),
            nullable=False,
            comment="Тип события внимания: active (пользователь перешёл на вкладку) или inactive (покинул вкладку)",
        ),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), nullable=False, comment="Точное время события в UTC (от браузера)"
        ),
        sa.CheckConstraint("event_type IN ('active', 'inactive')", name="valid_attention_event_type"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_domain_summaries",
        sa.Column("id", sa.Integer(), nullable=False, comment="Автоинкрементный ID записи"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column("domain", sa.String(length=255), nullable=False, comment="Домен, по которому собрана статистика"),
        sa.Column("date", sa.Date(), nullable=False, comment="Дата отчёта (без времени, в UTC)"),
        sa.Column(
            "total_seconds", sa.Integer(), nullable=False, comment="Суммарное время активного пребывания в секундах"
        ),
        sa.Column("active_count", sa.Integer(), nullable=False, comment="Количество переходов на домен за день"),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время генерации отчёта (UTC)",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domain_category_mapping",
        sa.Column(
            "domain",
            sa.String(length=255),
            nullable=False,
            comment="Домен в нижнем регистре без www (например: 'instagram.com')",
        ),
        sa.Column(
            "category_id", sa.Integer(), nullable=False, comment="Ссылка на категорию из таблицы domain_categories"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["domain_categories.id"],
        ),
        sa.PrimaryKeyConstraint("domain"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("domain_category_mapping")
    op.drop_table("daily_domain_summaries")
    op.drop_table("attention_events")
    op.drop_table("users")
    op.drop_table("domain_categories")
    # ### end Alembic commands ###
