"""Update base tables for events service

Revision ID: 117ffb063561
Revises: b1569ad77244
Create Date: 2025-11-21 15:02:57.907039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "117ffb063561"
down_revision: Union[str, Sequence[str], None] = "b1569ad77244"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_to_category",
        sa.Column(
            "domain",
            sa.String(length=255),
            nullable=False,
            comment="Домен в нижнем регистре (например: 'instagram.com')",
        ),
        sa.Column(
            "category_id", sa.Integer(), nullable=False, comment="Ссылка на категорию из таблицы domain_categories"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время создания связи (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время последнего обновления связи (UTC)",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["domain_categories.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("domain"),
    )
    op.create_index(op.f("ix_domain_to_category_category_id"), "domain_to_category", ["category_id"], unique=False)
    op.create_index(op.f("ix_domain_to_category_domain"), "domain_to_category", ["domain"], unique=False)
    op.drop_table("domain_category_mapping")
    op.drop_table("daily_domain_summaries")
    op.alter_column(
        "attention_events",
        "user_id",
        existing_type=sa.UUID(),
        comment="ID пользователя",
        existing_comment="ID пользователя, которому принадлежит событие",
        existing_nullable=False,
    )
    op.alter_column(
        "attention_events",
        "domain",
        existing_type=sa.VARCHAR(length=255),
        comment="Домен",
        existing_comment="Домен, на котором произошло событие",
        existing_nullable=False,
    )
    op.alter_column(
        "attention_events",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Точное время события в UTC",
        existing_comment="Точное время события в UTC (от браузера)",
        existing_nullable=False,
    )
    op.create_index(
        "idx_attention_events_user_domain_timestamp",
        "attention_events",
        ["user_id", "domain", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_attention_events_domain"), "attention_events", ["domain"], unique=False)
    op.create_index(op.f("ix_attention_events_timestamp"), "attention_events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_attention_events_user_id"), "attention_events", ["user_id"], unique=False)
    op.drop_constraint(op.f("attention_events_user_id_fkey"), "attention_events", type_="foreignkey")
    op.create_foreign_key(
        None, "attention_events", "users", ["user_id"], ["id"], onupdate="CASCADE", ondelete="CASCADE"
    )
    op.add_column(
        "domain_categories",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время создания категории (UTC)",
        ),
    )
    op.add_column(
        "domain_categories",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время последнего обновления категории",
        ),
    )
    op.alter_column(
        "domain_categories",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment="Уникальное имя категории",
        existing_comment="Уникальное имя категории (например: 'entertainment', 'work')",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("domain_categories_name_key"), "domain_categories", type_="unique")
    op.create_index(op.f("ix_domain_categories_name"), "domain_categories", ["name"], unique=True)
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время последнего обновления записи (UTC)",
        ),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Email для авторизации",
        existing_comment="Email для авторизации (может быть NULL для анонимов)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        comment="Хэш пароля",
        existing_comment="Хэш пароля (bcrypt/scrypt); NULL для анонимных пользователей",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время soft-delete",
        existing_comment="Время soft-delete (если не NULL — пользователь удалён)",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.create_unique_constraint(op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False)
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время soft-delete (если не NULL — пользователь удалён)",
        existing_comment="Время soft-delete",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        comment="Хэш пароля (bcrypt/scrypt); NULL для анонимных пользователей",
        existing_comment="Хэш пароля",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Email для авторизации (может быть NULL для анонимов)",
        existing_comment="Email для авторизации",
        existing_nullable=True,
    )
    op.drop_column("users", "updated_at")
    op.drop_index(op.f("ix_domain_categories_name"), table_name="domain_categories")
    op.create_unique_constraint(
        op.f("domain_categories_name_key"), "domain_categories", ["name"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "domain_categories",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment="Уникальное имя категории (например: 'entertainment', 'work')",
        existing_comment="Уникальное имя категории",
        existing_nullable=False,
    )
    op.drop_column("domain_categories", "updated_at")
    op.drop_column("domain_categories", "created_at")
    op.drop_constraint(None, "attention_events", type_="foreignkey")
    op.create_foreign_key(op.f("attention_events_user_id_fkey"), "attention_events", "users", ["user_id"], ["id"])
    op.drop_index(op.f("ix_attention_events_user_id"), table_name="attention_events")
    op.drop_index(op.f("ix_attention_events_timestamp"), table_name="attention_events")
    op.drop_index(op.f("ix_attention_events_domain"), table_name="attention_events")
    op.drop_index("idx_attention_events_user_domain_timestamp", table_name="attention_events")
    op.alter_column(
        "attention_events",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Точное время события в UTC (от браузера)",
        existing_comment="Точное время события в UTC",
        existing_nullable=False,
    )
    op.alter_column(
        "attention_events",
        "domain",
        existing_type=sa.VARCHAR(length=255),
        comment="Домен, на котором произошло событие",
        existing_comment="Домен",
        existing_nullable=False,
    )
    op.alter_column(
        "attention_events",
        "user_id",
        existing_type=sa.UUID(),
        comment="ID пользователя, которому принадлежит событие",
        existing_comment="ID пользователя",
        existing_nullable=False,
    )
    op.create_table(
        "daily_domain_summaries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False, comment="Автоинкрементный ID записи"),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False, comment="ID пользователя"),
        sa.Column(
            "domain",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Домен, по которому собрана статистика",
        ),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False, comment="Дата отчёта (без времени, в UTC)"),
        sa.Column(
            "total_seconds",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Суммарное время активного пребывания в секундах",
        ),
        sa.Column(
            "active_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Количество переходов на домен за день",
        ),
        sa.Column(
            "generated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("'2025-11-17 13:46:38.787842+00'::timestamp with time zone"),
            autoincrement=False,
            nullable=False,
            comment="Время генерации отчёта (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("daily_domain_summaries_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("daily_domain_summaries_pkey")),
    )
    op.create_table(
        "domain_category_mapping",
        sa.Column(
            "domain",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Домен в нижнем регистре без www (например: 'instagram.com')",
        ),
        sa.Column(
            "category_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Ссылка на категорию из таблицы domain_categories",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["domain_categories.id"], name=op.f("domain_category_mapping_category_id_fkey")
        ),
        sa.PrimaryKeyConstraint("domain", name=op.f("domain_category_mapping_pkey")),
    )
    op.drop_index(op.f("ix_domain_to_category_domain"), table_name="domain_to_category")
    op.drop_index(op.f("ix_domain_to_category_category_id"), table_name="domain_to_category")
    op.drop_table("domain_to_category")
    # ### end Alembic commands ###
