"""Add attempts column to VerificationCode table

Revision ID: ab269d920f0f
Revises: 4140bb20ebc4
Create Date: 2026-01-12 12:06:28.367385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab269d920f0f"
down_revision: Union[str, Sequence[str], None] = "4140bb20ebc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_codes",
        sa.Column(
            "attempts",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Количество неудачных попыток ввода кода",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_codes", "attempts")
    # ### end Alembic commands ###
