"""Add pending_email column to User table

Revision ID: 5528e8091ddd
Revises: ab269d920f0f
Create Date: 2026-01-15 10:52:28.900950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5528e8091ddd"
down_revision: Union[str, Sequence[str], None] = "ab269d920f0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("pending_email", sa.String(length=255), nullable=True, comment="Новый email для подтверждения"),
    )
    op.create_index(op.f("ix_users_pending_email"), "users", ["pending_email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_pending_email"), table_name="users")
    op.drop_column("users", "pending_email")
    # ### end Alembic commands ###
