"""Add VerificationCode table

Revision ID: 4140bb20ebc4
Revises: 117ffb063561
Create Date: 2026-01-12 09:39:44.218128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4140bb20ebc4"
down_revision: Union[str, Sequence[str], None] = "117ffb063561"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.Integer(), nullable=False, comment="Автоинкрементный ID кода"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column("code", sa.String(length=6), nullable=False, comment="Код подтверждения"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False, comment="Время истечения кода (UTC)"),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True, comment="Время использования кода (UTC)"),
        sa.Column(
            "last_sent_at", sa.DateTime(timezone=True), nullable=True, comment="Время последней отправки кода (UTC)"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
            comment="Время создания записи (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_verification_codes_user_code", "verification_codes", ["user_id", "code"], unique=False)
    op.create_index(op.f("ix_verification_codes_user_id"), "verification_codes", ["user_id"], unique=False)
    op.alter_column(
        "domain_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания записи (UTC)",
        existing_comment="Время создания категории (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время последнего обновления записи (UTC)",
        existing_comment="Время последнего обновления категории",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_to_category",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания записи (UTC)",
        existing_comment="Время создания связи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_to_category",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время последнего обновления записи (UTC)",
        existing_comment="Время последнего обновления связи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.drop_index(op.f("ix_domain_to_category_domain"), table_name="domain_to_category")
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True, comment="Логин пользователя"))
    op.add_column(
        "users",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Подтверждён ли email пользователя",
        ),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания записи (UTC)",
        existing_comment="Время регистрации (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время удаления записи (UTC)",
        existing_comment="Время soft-delete",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время soft-delete",
        existing_comment="Время удаления записи (UTC)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время регистрации (UTC)",
        existing_comment="Время создания записи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.drop_column("users", "is_verified")
    op.drop_column("users", "username")
    op.create_index(op.f("ix_domain_to_category_domain"), "domain_to_category", ["domain"], unique=False)
    op.alter_column(
        "domain_to_category",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время последнего обновления связи (UTC)",
        existing_comment="Время последнего обновления записи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_to_category",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания связи (UTC)",
        existing_comment="Время создания записи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время последнего обновления категории",
        existing_comment="Время последнего обновления записи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.alter_column(
        "domain_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Время создания категории (UTC)",
        existing_comment="Время создания записи (UTC)",
        existing_nullable=False,
        existing_server_default=sa.text("'2026-01-12 06:39:38.854865+00'::timestamp with time zone"),
    )
    op.drop_index(op.f("ix_verification_codes_user_id"), table_name="verification_codes")
    op.drop_index("idx_verification_codes_user_code", table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
