from ...common.common import StringEnum


class AuthErrorCode(StringEnum):
    """Коды ошибок сервиса авторизации."""

    # Validation errors (400) - ошибки валидации входных данных
    INVALID_USERNAME_FORMAT = "INVALID_USERNAME_FORMAT"
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT"
    INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE"

    # Conflict errors (409) - ресурс уже существует
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    # Business logic errors (422) - бизнес-валидация
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED"
    VERIFICATION_CODE_INVALID = "VERIFICATION_CODE_INVALID"
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"

    # Token errors (401) - ошибки аутентификации
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_MISSING = "TOKEN_MISSING"

    # Server errors (500) - внутренние ошибки сервера
    AUTH_SERVICE_ERROR = "AUTH_SERVICE_ERROR"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
