from ...common.common import StringEnum


class EventsErrorCode(StringEnum):
    """Коды ошибок events."""

    # Ошибки валидации 422
    INVALID_USER_ID = "EVT_INVALID_USER_ID"
    INVALID_EVENT_TYPE = "EVT_INVALID_EVENT_TYPE"
    INVALID_DOMAIN_FORMAT = "EVT_INVALID_DOMAIN_FORMAT"
    INVALID_DOMAIN_LENGTH = "EVT_INVALID_DOMAIN_LENGTH"
    INVALID_TIMESTAMP_FORMAT = "EVT_INVALID_TIMESTAMP_FORMAT"
    TIMESTAMP_IN_FUTURE = "EVT_TIMESTAMP_IN_FUTURE"

    # Ошибки сервера 500
    USER_CREATION_FAILED = "EVT_USER_CREATION_FAILED"
    EVENTS_INSERT_FAILED = "EVT_EVENTS_INSERT_FAILED"
    DATA_INTEGRITY_VIOLATION = "EVT_DATA_INTEGRITY_VIOLATION"
    TRANSACTION_FAILED = "EVT_TRANSACTION_FAILED"
