from ...common.common import StringEnum


class EventsErrorCode(StringEnum):
    """Коды ошибок events."""

    # Ошибки валидации 422
    INVALID_USER_ID = "INVALID_USER_ID"
    INVALID_EVENT_TYPE = "INVALID_EVENT_TYPE"
    INVALID_DOMAIN_FORMAT = "INVALID_DOMAIN_FORMAT"
    INVALID_DOMAIN_LENGTH = "INVALID_DOMAIN_LENGTH"
    INVALID_TIMESTAMP_FORMAT = "INVALID_TIMESTAMP_FORMAT"
    TIMESTAMP_IN_FUTURE = "TIMESTAMP_IN_FUTURE"
    ANON_EVENTS_LIMIT_EXCEEDED = "ANON_EVENTS_LIMIT_EXCEEDED"
    TOO_MANY_EVENTS = "TOO_MANY_EVENTS"
    EMPTY_EVENTS_LIST = "EMPTY_EVENTS_LIST"

    # Ошибки сервера 500
    USER_CREATION_FAILED = "USER_CREATION_FAILED"
    EVENTS_INSERT_FAILED = "EVENTS_INSERT_FAILED"
    DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION"
    TRANSACTION_FAILED = "TRANSACTION_FAILED"
